In [11]:
import numpy as np

def convolve2d(image, kernel):
    # Get shapes of image and kernel
    i_height, i_width = image.shape
    k_height, k_width = kernel.shape
    print("k_height: ", k_height)   
    print("k_width: ", k_width)
    # Calculate output dimensions
    o_height = i_height - k_height + 1
    o_width = i_width - k_width + 1
    print("o_height: ", o_height)
    print("o_width: ", o_width)
    
    # Create output array
    output = np.zeros((o_height, o_width))
    
    # Perform convolution
    for y in range(o_height):
        for x in range(o_width):
            output[y, x] = np.sum(image[y:y+k_height, x:x+k_width] * kernel)

            # print("output[y, x]: ", output[y, x])
            # print("image[y:y+k_height, x:x+k_width]: ", image[y:y+k_height, x:x+k_width])
            # print("kernel: ", kernel)
    
    return output



In [12]:
# Example usage
image = np.random.rand(5, 5)
print("image:", image)
kernel = np.random.rand(3, 3)
print("kernel:", kernel)
result = convolve2d(image, kernel)
print("result:", result)

image: [[0.06390142 0.23142642 0.38603808 0.59167518 0.76593912]
 [0.45149096 0.5395306  0.04924935 0.54191957 0.21702728]
 [0.07575175 0.90515236 0.84982739 0.57774819 0.30597216]
 [0.81863314 0.57267457 0.68129306 0.41637146 0.48143063]
 [0.00847709 0.52846705 0.65353477 0.56532141 0.52527172]]
kernel: [[0.67079771 0.19872358 0.32201367]
 [0.15976258 0.56247484 0.30203298]
 [0.65978674 0.31243383 0.32986174]]
k_height:  3
k_width:  3
o_height:  3
o_width:  3
output[y, x]:  1.2167487920176316
image[y:y+k_height, x:x+k_width]:  [[0.06390142 0.23142642 0.38603808]
 [0.45149096 0.5395306  0.04924935]
 [0.07575175 0.90515236 0.84982739]]
kernel:  [[0.67079771 0.19872358 0.32201367]
 [0.15976258 0.56247484 0.30203298]
 [0.65978674 0.31243383 0.32986174]]
output[y, x]:  1.7533579508637092
image[y:y+k_height, x:x+k_width]:  [[0.23142642 0.38603808 0.59167518]
 [0.5395306  0.04924935 0.54191957]
 [0.90515236 0.84982739 0.57774819]]
kernel:  [[0.67079771 0.19872358 0.32201367]
 [0.15976258 0.5

In [14]:
# code

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Slicing rows

# Get the first row
row_1 = matrix[0, :]  
print(row_1)  

# Slicing columns

 # Get the second column
col_2 = matrix[:, 1] 
print(col_2)  


[1 2 3]
[2 5 8]


In [21]:
print(matrix[:, 1:3])  # Get the 2x2 matrix in the bottom right corner

[[2 3]
 [5 6]
 [8 9]]


In [22]:
print(matrix[1:3, :])  # Get the 2x2 matrix in the middle

[[4 5 6]
 [7 8 9]]


In [23]:
print(matrix[1:3, 1:3])  # Get the 2x2 matrix in the middle

[[5 6]
 [8 9]]
